### ISSUE TITLE
Dask ml with light gbm And gridsearchcv Assertion error

### ISSUE THREAD

**Issue by Sajjad1989** [dask/dask-ml#683] opened 2020-06-17 13:01 UTC
Lgbm=daskgridcv (model,Param grid)
With joblib.parallel_backend('dask')
      Lgbm.fit(strain,ytrain)

I get assertion Error could anyone please let me know why I am I getting this error

**Comment by TomAugspurger** [comment] 2020-06-17 13:07
See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for writing bug reports.

**Comment by TomAugspurger** [comment] 2020-08-05 20:35
Duplicate of https://github.com/dask/dask-ml/issues/684.

**Closed by TomAugspurger** 2020-08-05 20:35 UTC
