### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask-ml#946] opened 2022-10-19 18:40 UTC
`dask` / `distributed` / `scikit-learn` all have Python 3.10 support at this point. We should add support for `dask-ml` too

**Comment by hungbui-io** [comment] 2023-03-07 03:26
Hi @jrbourbeau , I am wondering do you know when will dask-ml new version be released, the one that supports python 3.10?

**Comment by jrbourbeau** [comment] 2023-03-24 21:36
Thanks for the ping @hungbui-io. In addition to Python 3.10 support, it'd also be good to get a new release out for supporting recent versions of `sklearn`. 

@TomAugspurger is this something you have bandwidth for?

**Comment by TomAugspurger** [comment] 2023-03-24 21:57
Sure, just fixing some metadata in https://github.com/dask/dask-ml/pull/966 quick (hopefully).

**Comment by TomAugspurger** [comment] 2023-03-24 22:06
Created https://github.com/dask/dask-ml/releases/tag/v2023.3.24. https://github.com/dask/dask-ml/actions/runs/4515711405/jobs/7953319610 is releasing to PyPI.

We'll want to bump the python version in the conda-forge package before that's merged.

**Closed by TomAugspurger** 2023-03-24 22:06 UTC

**Comment by jrbourbeau** [comment] 2023-03-25 00:36
Thanks @TomAugspurger!

**Comment by hungbui-io** [comment] 2023-04-06 07:29
@jrbourbeau @TomAugspurger  Thanks for the update. However, I am still facing an issue with 2023.3.24 release when import dask_ml due to the conflict with dask.distributed. Can you pls have a look on this?
Here is the error:
`Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask_ml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\...\site-packages\dask_ml\__init__.py", line 4, in <module>
    from dask_ml.model_selection import _normalize
  File "C:\Users\...\site-packages\dask_ml\model_selection\__init__.py", line 6, in <module>
    from ._hyperband import HyperbandSearchCV
  File "C:\Users\...\site-packages\dask_ml\model_selection\_hyperband.py", line 12, in <module>
    from ._incremental import BaseIncrementalSearchCV
  File "C:\Users\...\site-packages\dask_ml\model_selection\_incremental.py", line 19, in <module>
    from dask.distributed import Future, default_client, futures_of, wait
ImportError: cannot import name 'Future' from 'dask.distributed' (C:\Users\...\site-packages\dask\distributed.py)`

**Comment by TomAugspurger** [comment] 2023-04-06 11:15
You might try installing things in a new environment to see if the problem is reproducible.
