### ISSUE TITLE
KMeans fit TypeError expected dtype object, got 'numpy.dtype[float64]'

### ISSUE THREAD

**Issue by Maia97** [dask/dask-ml#802] opened 2021-03-05 08:09 UTC
**What happened**:
when fit X, get error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-11-7d3bc4c475f7> in <module>
      1 km = dask_ml.cluster.KMeans(n_clusters=3, init_max_iter=2, oversampling_factor=10)
----> 2 km.fit(X)
 ...
 ...
 TypeError: expected dtype object, got 'numpy.dtype[float64]'
```

**What you expected to happen**:
output:
` KMeans(init_max_iter=2, n_clusters=3, oversamplinh_factor=10)`

**Minimal Complete Verifiable Example**:

```python
import dask_ml.cluster

X, y = dask_ml.datasets.make_blobs(n_samples=1000000,
                                   chunks=100000,
                                   random_state=0,
                                   centers=3)
km = dask_ml.cluster.KMeans(n_clusters=3, init_max_iter=2, oversampling_factor=10)
km.fit(X)
```

**Environment**:

- Dask version: dask_ml 1.8.0, dask 2021.02.0
- Python version: 3.7
- Operating System: MacOS Catalina 10.15.5
- Install method (conda, pip, source): conda
- Other packages: numpy 1.20.1, pandas 1.2.2

**Comment by TomAugspurger** [comment] 2021-03-14 13:02
Can you search on the Dask / distributed issue trackers for similar issues? I vaguely recall similar issues but can't find them right now.

**Comment by Mimran0715** [comment] 2021-03-20 23:51
I'm also having a similar issue. I think #803 is closed but not sure how to get rid of TypeError.

**Comment by hristog** [comment] 2021-03-21 00:04
Hi @Maia97,

I _think_ the series of issues and PRs that @TomAugspurger has referred to is as follows:
- https://github.com/dask/dask/pull/6430 / https://github.com/dask/dask/issues/6330
- https://github.com/numpy/numpy/pull/14882
- https://github.com/pydata/sparse/issues/383
- https://github.com/numba/numba/issues/6041 / https://github.com/numba/numba/pull/6078

I've tried a few combinations of different versions of `dask`, `numpy` and `numba`, _but_ on Python 3.8, and I haven't been able to reproduce the issue.

Could you, please, try to update to the latest version of `numba` and then attempt to run your example again?
If this doesn't help, could you provide the version number for `numba` and also the entire `Traceback`, please?

I think this issue can be labeled as "Needs Info" in the meantime.

**Comment by hristog** [comment] 2021-03-21 00:11
Hi @Mimran0715,

I wrote in #803 that it might be possibly related to #802, but having discovered the aforementioned series of issues, I believe that #802 and #803 are unrelated.

If you could, please, provide some info about the underlying package versions in your environment and a `Traceback`, it would be greatly appreciated, and help discover the root cause sooner.

Thanks!

**Comment by Mimran0715** [comment] 2021-03-21 02:27
Thanks for responding. I'm just trying to run the K-means cluster example here: https://examples.dask.org/machine-learning/training-on-large-datasets.html
Here is the Traceback:
<img width="1118" alt="Screen Shot 2021-03-20 at 7 25 19 PM" src="https://user-images.githubusercontent.com/20411845/111891710-0f5eff00-89b2-11eb-8b3e-8afa8f218e39.png">
Here are some details abt the package versions:
<img width="552" alt="Screen Shot 2021-03-20 at 7 26 49 PM" src="https://user-images.githubusercontent.com/20411845/111891742-40d7ca80-89b2-11eb-82dd-68575d183309.png">

**Comment by hristog** [comment] 2021-03-21 09:27
Thanks for the further info provided, @Mimran0715!

I confirm I've been able to locally reproduce the issue with the following versions:
- numpy==1.20.1
- pandas==0.25.1
- numba==0.50.0 (was running into https://github.com/mkocabas/VIBE/issues/88 and https://github.com/numba/numba/issues/5415 with 0.45.1)
- llvmlite==0.32.1
- dask==2.5.2
- dask-glm==0.2.0
- dask-ml==1.8.0
- Python 3.7.3

As suggested in my comment [above](https://github.com/dask/dask-ml/issues/802#issuecomment-803488059), this was resolved via upgrading `numba` to the latest available version. I just did `python3 -m pip install numba==0.53.0`, and this has enabled me to run the K-Means|| example.

Please, have a go at upgrading the `numba` version (you _might_ need to update `llvmlite` to something compatible as well, e.g., `0.32.1`; if you do, please, take a note of your current version of `llvmlite`, so that you can always revert back later on, if needs be). If you don't want to globally affect your local versions, you can test with an updated version of `numba` via [venv](https://docs.python.org/3/tutorial/venv.html) or via a Docker container.

Thanks!

**Comment by jrbourbeau** [comment] 2021-03-22 16:29
Should be closed by https://github.com/dask/dask-ml/pull/809. @Maia97 feel free to re-open if that's not the case

**Closed by jrbourbeau** 2021-03-22 16:29 UTC
